version: 1.0.{build}
clone_script:
- cmd: >-
    set REPO_PATH=%APPVEYOR_REPO_NAME%

    IF NOT "%REPO_PATH:~0,8%"=="https://" set REPO_PATH=https://github.com/%APPVEYOR_REPO_NAME%.git

    git clone -q --branch=%APPVEYOR_REPO_BRANCH% %REPO_PATH% %APPVEYOR_BUILD_FOLDER%

    git submodule update --init

    rem git fetch origin pull/XXX/merge && git checkout FETCH_HEAD

    git --no-pager log --pretty=oneline -1
image: Visual Studio 2015
environment:
  matrix:
  - GENERATOR: '"MinGW Makefiles"'
    BUILD_TYPE: Debug
    QT_PATH: C:\Qt\5.8\mingw53_32
  - GENERATOR: '"MinGW Makefiles"'
    BUILD_TYPE: Release
    QT_PATH: C:\Qt\5.8\mingw53_32
  - GENERATOR: '"Visual Studio 14 2015"'
    BUILD_TYPE: Debug
    QT_PATH: C:\Qt\5.8\msvc2015
  - GENERATOR: '"Visual Studio 14 2015"'
    BUILD_TYPE: Release
    QT_PATH: C:\Qt\5.8\msvc2015
  - GENERATOR: '"Visual Studio 14 2015 Win64"'
    BUILD_TYPE: Debug
    QT_PATH: C:\Qt\5.8\msvc2015_64
  - GENERATOR: '"Visual Studio 14 2015 Win64"'
    BUILD_TYPE: Release
    QT_PATH: C:\Qt\5.8\msvc2015_64
build_script:
- cmd: >-
    set

    mkdir build

    cd build

    set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

    set PATH=C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;%PATH%

    cmake .. -G %GENERATOR% -DCMAKE_PREFIX_PATH=%QT_PATH% -DCMAKE_BUILD_TYPE=%BUILD_TYPE%

    cmake --build . --config %BUILD_TYPE%
test: off
